#!/bin/sh
net_eth0_mode="dhcp"
net_eth0_ip=""
net_eth0_gateway=""
net_eth0_broadcast=""
net_eth0_netmask=""
net_eth0_dns1=""
net_eth0_dns2=""

if [ "$net_eth0_ip" == "" ]
then
	net_eth0_ip="$(ifconfig eth0 | awk 'NR==2 {print $2}' | cut -d: -f2)"
fi

if [ "$net_eth0_gateway" == "" ]
then
	net_eth0_gateway="$(route -n | awk 'NR==4 {print $2}')"
fi

if [ "$net_eth0_broadcast" == "" ]
then
	net_eth0_broadcast="$(ifconfig eth0 | awk 'NR==2 {print $3}' | cut -d: -f2)"
fi

if [ "$net_eth0_netmask" == "" ]
then
	net_eth0_netmask="$(ifconfig eth0 | awk 'NR==2 {print $4}' | cut -d: -f2)"
fi

if [ "$net_eth0_dns1" == "" ]
then
	net_eth0_dns1="$(cat /etc/resolv.conf | grep nameserver | awk 'NR==1 {print $2}')"
fi

if [ "$net_eth0_dns2" == "" ]
then
	net_eth0_dns2="$(cat /etc/resolv.conf | grep nameserver | awk 'NR==2 {print $2}')"
fi
