#!/bin/sh

set -e

DESC="mt-daapd"
NAME=mt-daapd
DAEMON=/usr/sbin/$NAME

case "$1" in
	start)
		echo -n "Starting mt-daapd "
		mv /var/log/mt-daapd.log /var/log/mt-daapd.0.log
		start-stop-daemon -S -b -x $NAME
		echo "OK"
		;;
	stop)
		echo -n "Stopping mt-daapd "
		start-stop-daemon -K -x $NAME
		echo "OK"
		;;
	restart|force-reload)
		echo "Restarting $DESC: "
		$0 stop
		sleep 1
		$0 start
		echo "OK"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
