#!/bin/sh
. /frontend/config/network
. /frontend/cli/functions

tmpfile="/tmp/clishell"
trap "" 2 20
run="1"

while [ "$run" == "1" ]
do
	dialog --backtitle "HotNAS CLI Fallback" \
		   --menu "Please choose an option." 12 40 11 \
		   "1." "View network config" \
		   "2." "Set network config" \
		   "3." "Root shell" \
		   "4." "Reboot system" \
		   "5." "Shutdown system" \
		   "6." "Exit shell" 2> $tmpfile
		   
	result=$(cat $tmpfile)

	case "$result" in
		"1.")
			getcurrent_network_settings
			
			dialog --backtitle "HotNAS CLI Fallback" \
				   --msgbox "View network config\n\nNetwork mode: $net_eth0_mode\nIP Address: $net_eth0_ip\nGateway: $net_eth0_gateway\nBroadcast: $net_eth0_broadcast\nNetmask: $net_eth0_netmask\nSearch domain: $net_eth0_domain\nDNS1: $net_eth0_dns1\nDNS2: $net_eth0_dns2" \
							 20 40
			;;
		"2.")
			getcurrent_network_settings
			
			dialog --backtitle "HotNAS CLI Fallback" \
				   --menu "Please choose a network mode" 12 40 11 \
				   "1." "DHCP" \
				   "2." "Static" 2> $tmpfile
			result=$(cat $tmpfile)
			
			if [ "$result" == "2." ]
			then
				net_eth0_mode="static"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "IP Address:" 10 50 "$net_eth0_ip" \
					   2> $tmpfile
				
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)"
				net_eth0_ip="$result"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "Gateway:" 10 50 "$net_eth0_gateway" \
					   2> $tmpfile
				
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)"
				net_eth0_gateway="$result"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "Broadcast:" 10 50 "$net_eth0_broadcast" \
					   2> $tmpfile
				
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)" 
				net_eth0_broadcast="$result"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "Netmask:" 10 50 "$net_eth0_netmask" \
					   2> $tmpfile
				
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)"
				net_eth0_netmask="$result"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "Search domain:" 10 50 "$net_eth0_domain" \
					   2> $tmpfile
				
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)"
				net_eth0_domain="$result"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "DNS1:" 10 50 "$net_eth0_dns1" \
					   2> $tmpfile
				
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)"
				net_eth0_dns1="$result"
				
				dialog --backtitle "HotNAS CLI Fallback" \
					   --inputbox "DNS2:" 10 50 "$net_eth0_dns2" \
					   2> $tmpfile
		
				if [ "$?" == "1" ]
				then
					continue
				fi
				
				result="$(cat $tmpfile)"
				net_eth0_dns2="$result"
				
				save_network_settings
				apply_network_settings
				/etc/init.d/S40network restart &> /var/log/networksetup.log
				
				if [ "$?" == "0" ]
				then
					dialog --backtitle "HotNAS CLI Fallback" \
						   --msgbox "New network settings applied.\nWeb frontend can be accessed at http://$net_eth0_ip" \
							20 40
				else
					dialog --backtitle "HotNAS CLI Fallback" \
						   --msgbox "New settings failed to apply.\nPlease launch root shell and view /var/log/networksetup.log." \
							20 40
				fi
			else
				net_eth0_mode="dhcp"
				
				save_network_settings
				apply_network_settings
				/etc/init.d/S40network restart &> /var/log/networksetup.log
				
				if [ "$?" == "0" ]
				then
					dialog --backtitle "HotNAS CLI Fallback" \
						   --msgbox "New network settings applied.\nWeb frontend can be accessed at http://$net_eth0_ip" \
							20 40
				else
					dialog --backtitle "HotNAS CLI Fallback" \
						   --msgbox "New settings failed to apply.\nPlease launch root shell and view /var/log/networksetup.log." \
							20 40
				fi
			fi					
			;;
		"3.")
			sh
			;;
		"4.")
			reboot
			;;
		"5.")
			poweroff
			;;
		"6.")
			run="0"
			;;
		*)
			continue
			;;	   
	esac
done

exit 0
